In [172]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_table('sample_data/input_9.txt',header = None)
n = data.shape[0]
m = n

In [138]:
# matrix with test input
data_t = []

i = 0
for i in range(n):
  data_t.append([int(j) for j in data[0][i].split(',')])

dat_mat = np.asmatrix(data_t)

In [173]:
# matrix with input
data_t = []
for i in range(n):
  data_t.append([int(j) for j in data[0][i]])

dat_mat = np.asmatrix(data_t)

In [175]:
total = 0
low_points = []
n = dat_mat.shape[0]
m = dat_mat.shape[1]
for i in range(n):
  for j in range(m):
    cond = True
    if i > 0 :
      cond = cond and dat_mat[i,j] < dat_mat[i - 1,j]
    if i < (n-1):
      cond = cond and dat_mat[i,j] < dat_mat[i + 1,j] 
    if j > 0:
      cond = cond and dat_mat[i,j] < dat_mat[i,j - 1]
    if j < (m-1):
      cond = cond and dat_mat[i,j] < dat_mat[i,j + 1]
    
    if cond:
      
      low_points.append([i,j])
      total = total + 1 + dat_mat[i,j]

total

580

In [176]:
def basin(x,y,n,m):
  neighbors = []
  if [x,y] not in neighbors:
    neighbors.append([x,y])
  if x > 0:
    if dat_mat[x,y] < dat_mat[x - 1,y] and dat_mat[x - 1,y] < 9 and [x-1,y] not in neighbors:
      neighbors.extend(basin(x-1,y,n,m))
  if x < (n-1):
    if dat_mat[x,y] < dat_mat[x + 1,y] and dat_mat[x + 1,y] < 9 and [x+1,y] not in neighbors:
      neighbors.extend(basin(x+1,y,n,m))
  if y > 0:
    if dat_mat[x,y] < dat_mat[x,y - 1 ] and dat_mat[x,y - 1] < 9 and [x,y - 1] not in neighbors:
      neighbors.extend(basin(x,y-1,n,m))
  if y < (m-1):
    if dat_mat[x,y] < dat_mat[x,y + 1] and dat_mat[x,y + 1] < 9 and [x,y + 1] not in neighbors:
      neighbors.extend(basin(x,y+1,n,m))
  return neighbors

In [177]:
# part 2 

len_basin = []

for j in range(len(low_points)):
  [x,y] = low_points[j]
  test_list = basin(x,y,n,m)
  res = []
  for i in test_list:
    if i not in res:
        res.append(i)
  len_basin.append(len(res))
  
len_basin

[3,
 2,
 2,
 15,
 2,
 34,
 18,
 10,
 6,
 11,
 24,
 7,
 45,
 15,
 8,
 20,
 26,
 2,
 42,
 56,
 17,
 6,
 51,
 58,
 56,
 33,
 26,
 7,
 12,
 13,
 2,
 46,
 65,
 25,
 7,
 2,
 27,
 22,
 24,
 98,
 2,
 11,
 28,
 59,
 28,
 89,
 9,
 52,
 42,
 25,
 20,
 6,
 53,
 22,
 73,
 67,
 28,
 13,
 29,
 12,
 35,
 10,
 7,
 55,
 20,
 31,
 10,
 61,
 26,
 2,
 14,
 2,
 12,
 31,
 64,
 19,
 24,
 15,
 31,
 56,
 24,
 8,
 22,
 26,
 4,
 16,
 27,
 8,
 47,
 42,
 78,
 14,
 85,
 9,
 78,
 23,
 34,
 44,
 22,
 33,
 7,
 9,
 4,
 70,
 29,
 22,
 11,
 14,
 46,
 53,
 16,
 36,
 29,
 17,
 73,
 42,
 9,
 12,
 4,
 13,
 69,
 4,
 42,
 19,
 58,
 93,
 31,
 4,
 37,
 37,
 2,
 30,
 49,
 83,
 37,
 81,
 12,
 5,
 32,
 26,
 46,
 2,
 67,
 17,
 15,
 22,
 10,
 10,
 16,
 79,
 75,
 25,
 4,
 48,
 54,
 33,
 79,
 43,
 4,
 13,
 94,
 43,
 80,
 6,
 6,
 7,
 12,
 7,
 2,
 75,
 5,
 19,
 51,
 82,
 16,
 3,
 49,
 5,
 9,
 54,
 6,
 59,
 20,
 34,
 26,
 6,
 46,
 9,
 9,
 5,
 13,
 7,
 3,
 2,
 41,
 3,
 67,
 15,
 7,
 77,
 4,
 10,
 27,
 17,
 30,
 28,
 48,
 23,
 48,
 47,
 4,
 62,
 64,
 51,
 17,
 7,
 17,
 93,
 16,
 6,
 17,
 80,
 4,
 4,
 58,
 16,
 46,
 69,
 14,
 29,
 25,
 27,
 5,
 59,
 20,
 15,
 37,
 8,
 52,
 14,
 14,
 15,
 32,
 32,
 8,
 9,
 8,
 31,
 6,
 2,
 6]

In [178]:
res = 1
for i in range(3):
  tmax = max(len_basin)
  print(tmax)
  len_basin.remove(tmax)
  res = res * tmax
res

98
94
93

856716